services:
  - type: web
    name: tubulaotermico
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server_local:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
